### PR TITLE
Refactor native classes

### PR DESCRIPTION
**Pull request by pernambucano**
### What does this PR do?

It converts some files to use native classes.

### Which issues does this PR fix or reference?

#197 

### Proof of work

> e.g. screenshot

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] I've added unit and/or integration tests if any code was added
- [X] I've checked for errors using "yarn test"

### CODE REVIEW

**Review by acorncom — APPROVED** [review]
Looks good to me

**Comment by pernambucano** [comment]
@ijlee2 , do you think this would be a good template for PRs ? Is there anything you'd add to it? Btw, thanks for the guidance! This is a welcoming community indeed. 😃

**Comment by milindalvares** [comment]
Looks right @pernambucano :)

**Comment by acorncom** [comment]
@pernambucano if you want to send in a PR for that to be a template, we can talk about it. There have been different opinions on whether having those types of templates is friendly or not to folks coming in, I'm not sure what the latest consensus on that is. But happy to see a PR that we can discuss for that

**Comment by pernambucano** [comment]
Thanks a lot for the feedback, @acorncom ! I'll create a PR to get things started then.

**Comment by ijlee2** [comment]
@pernambucano Yep, the PR description looks good!

**Pull request merged**
