### PR TITLE
Add percy testing

### PR DESCRIPTION
**Pull request by jenweber**
Let's see if this works!

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @jenweber. I was wondering if your pull request is ready for review? I wasn't sure as I'm not seeing Percy in the list of checks that passed.

**Comment by jenweber** [comment]
This is not ready for review. I seem to have missed something in the setup, since I can't see any results. I'll need to keep working on this.

**Comment by ijlee2** [comment]
I think you will want to update the scripts. In particular, the `test` script should have `percy exec ---`.

```json
"scripts": {
  "build": "ember build --environment=production",
  "lint:hbs": "ember-template-lint .",
  "lint:js": "eslint .",
  "start": "ember serve",
  "test": "percy exec --- ember test"
},
```

https://docs.percy.io/docs/ember#setup

**Comment by ijlee2** [comment]
Hi, @jenweber. I updated dependencies to their latest so you may want to reset your commits and cherry-pick ones that pertain to Percy. Apologies for the inconvenience.

**Comment by jenweber** [comment]
Closed in favor of https://github.com/ember-learn/ember-help-wanted/issues/187

**Pull request closed without merging**
