### PR TITLE
Apply website redesign

### PR DESCRIPTION
**Pull request by jayjayjpg**
Closes https://github.com/ember-learn/ember-help-wanted/issues/150

Review the new layout over at https://deploy-preview-152--ember-help-wanted.netlify.app/ or by checking out this feature branch locally.

### CODE REVIEW

**Comment by MelSumner** [comment]
@jayjayjpg could you update the branch? And, do you need any additional help to move this out of draft?

**Comment by jayjayjpg** [comment]
@MelSumner Thank you for the nudge! I just updated the feature branch and it should be ready for review over at Netlify (and for testing the `issues` sub route, it's best to test locally)

**Comment by MelSumner** [comment]
@jayjayjpg I noticed in the netlify preview that the issues themselves aren't showing up like they are on the current site published to production. Is that an in-progress glitch?

**Comment by jayjayjpg** [comment]
@MelSumner That's correct and I just had another look at the CORS settings for the backend on Heroku, which needed an update to accommodate for a new url scheme on netlify previews apps it seems. I think this should resolve the issue now: (https://deploy-preview-152--ember-help-wanted.netlify.app/learning)

If something else is missing, feel free to let me know and I can investigate! And thank you for taking the time to review in the first place :bowing_woman:

**Comment by MelSumner** [comment]
Ahh perfect. It looks great, thank you for working on this!

**Pull request merged**
